service: lambda-spring

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  memorySize: 256
  timeout: 20
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}

package:
  artifact: target/lambda-spring.jar

functions:
  spring:
    handler: de.serverlessbuch.lambda.LambdaHandler
    events:
      - http:
          path: /{proxy+}
          method: any
